# Codecov Configuration
# https://docs.codecov.io/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"
  
  status:
    project:
      default:
        target: 60%
        threshold: 2%
        if_ci_failed: error
    
    patch:
      default:
        target: 70%
        threshold: 5%

# Ignore certain paths for coverage
ignore:
  - "node_modules/**"
  - "src/test/**"
  - "src/main.jsx"
  - "**/*.config.js"
  - "**/*.d.ts"

# Comment on PR with coverage report
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Flags for different test types
flags:
  unittests:
    paths:
      - src/
    carryforward: true

# GitHub Checks
github_checks:
  annotations: true


